name: Auto Check JSON Comments

on:
  push:
    branches:
      - master

jobs:
  feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Check GitHub CLI version
        run: gh --version
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("jsonlite", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("dplyr", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("purrr", repos="https://cloud.r-project.org")'

      - name: Run feedback script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls 
          chmod +x ./scripts/issue_check.sh
          ./scripts/issue_check.sh
          