name: Auto Check JSON Comments

on:
  push:
    branches:
      - master  # Runs when pushing to the main branch
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Check GitHub CLI version
        run: gh --version
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install pak
        run: |
          Rscript -e "install.packages('pak', repos = 'https://r-lib.github.io/p/pak/devel/')"

      - name: Install specific R packages
        run: |
          Rscript -e "pak::pak(c('httr', 'dplyr', 'tibble','purrr', 'jsonlite'))"
      
      - name: Check if httr is installed
        run: |
          Rscript -e "if (!requireNamespace('httr', quietly = TRUE)) { stop('httr is NOT installed') } else { message('httr is installed') }"    
      
      - name: Run issue check script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls 
          chmod +x ./scripts/issue_check.sh
          ./scripts/issue_check.sh

      - name: Check if report.tsv exists
        run: |
          if [ -f "report.tsv" ]; then
            echo "report.tsv exists"
          else
            echo "report.tsv does not exist"
            exit 1  # Fail the job if the file is missing
          fi

      - name: Run issue check script
        run: |
            ls 
            chmod +x ./scripts/create_issue_label.sh
            ./scripts/create_issue_label.sh
  