name: R Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'  # or 'release' for latest
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    
    - name: Install R dependencies
      run: |
        R -e "install.packages(c('testthat', 'devtools'), repos='https://cran.rstudio.com/')"
        # Add any other packages your scripts need here
        # R -e "install.packages(c('dplyr', 'jsonlite'), repos='https://cran.rstudio.com/')"
    
    - name: Run tests
      run: |
        cd tests
        Rscript tests.R
